MVC/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using MVC.ViewModels;

namespace MVC.Controllers
{
    public class PeopleController : Controller
    {
        public static PeopleViewModel staticM = new PeopleViewModel();

      
        public IActionResult Index()
        {
            staticM.CreatePeopleList();
            return View(staticM);
        }

        [HttpPost]

        public IActionResult Search(PeopleViewModel mo)
        {
            if (mo.SearchFilter.Length > 0)
            {
               
                mo.Drivers = staticM.Drivers.Where(item => (item.Name.Contains(mo.SearchFilter) || item.City.Name.Contains(mo.SearchFilter))).ToList();
                return View("Index",mo);
            }

         
            return View("Index", staticM);


        }


        [HttpPost]

        public IActionResult Add(PeopleViewModel m)
        {
            int _id = staticM.Drivers.Count();
            if (ModelState.IsValid)
            {
                Person p = new Person();
                p.Name = m.Name;
                p.Phone = m.Phone;
                p.CityId = m.City.Id;
                p.Id = ++_id;
                staticM.Drivers.Add(p);
                

            }
            return View("Index", staticM);


        }



            [HttpGet]
            public IActionResult Delete(int id)
            {
                PeopleViewModel m = new();
                m.Drivers = m.Drivers.Where(item => item.Id == (id)).ToList();
                if (m.Drivers.Count != 0)
                {
                    m.Drivers.Remove(m.Drivers[0]);
                }

                return View("Person", staticM);
            }
        }

    }

MVC/Controllers/RoleController.cs
using MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MVC.Controllers
{

    //[Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        readonly RoleManager<IdentityRole> _roleManager;
        readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            role.NormalizedName = role.Name.ToUpper();
            await _roleManager.CreateAsync(role);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            await _roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

        public IActionResult AddUserToRole()
        {
            ViewBag.Users = new SelectList(_userManager.Users, "Id", "UserName");
            ViewBag.Roles = new SelectList(_roleManager.Roles, "Name", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddUserToRole(string userId, string roleName)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.AddToRoleAsync(user, roleName);

            return RedirectToAction("Index");
        }

        public IActionResult ShowAllUsers()
        {
            return View(_userManager.Users);
        }

        public async Task<IActionResult> ShowUserRoles(string Id)
        {
            UserRoleViewModel vm = new UserRoleViewModel();
            var user = await _userManager.FindByIdAsync(Id);

            var assignedRoles = new List<string>(await _userManager.GetRolesAsync(user));
            vm.UserId = Id;
            vm.UserName = user.UserName;

            vm.Roles.AddRange(assignedRoles);

            return View(vm);
        }
        public async Task<IActionResult> RemoveRoleFromUser(string rolename, string userid)
        {
            var user = await _userManager.FindByIdAsync(userid);
            await _userManager.RemoveFromRoleAsync(user, rolename);
            return RedirectToAction("ShowUserRoles", new { id = userid });
        }

    }
}

MVC/Views/Shared/_AjaxPerson.cshtml
@model PeopleViewModel

<div class="row p-3">
    <div class="col">
        <div class="row bg-gradient bg-opacity-55 bg-info header-table">
            <div class="col">ID</div>
            <div class="col">Name</div>
            <div class="col">City</div>
            <div class="col">Phone</div>
        </div>

       @foreach(var person in @Model.Drivers){
    
      
      <partial name="~/Views/Shared/_PartialPerson.cshtml" model="@person" />
     
}       

    </div>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Index</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>                      
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Cities</a>                        
                        </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Countries</a>                        
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="languages" asp-action="Index">Languages</a>                        
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>                        
                           </li>
                        @if (User.IsInRole("Admin"))
                        {
                            
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">ShowAllUsers</a>  
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">ShowlUserRoles</a>  
                        </li> 
                         }
                          
                              <partial name="_LoginPartial"/>
                        
                    </ul>
                </div>
            </div>
        </nav>
        
    </header>
     

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           @DateTime.Now.ToString("yy-MM-dd")  (C) Abdirahman Haji
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC/Views/Shared/_PartialPerson.cshtml
@model Person

<div class="row">
    
    <div class="col">@Model.Id</div>
    <div class="col">@Model.Name</div>
    <div class="col">@Model.Phone</div>
     <div class="col">@Model.City</div>
</div>